### ISSUE TITLE
API URLs should probably be formatted using url-encoded strings.

### ISSUE THREAD

**Issue by mattbasta** [ajmyers/Sublime-TM1#1]
When constructing URLs (like [this](https://github.com/ajmyers/Sublime-TM1/blob/master/include/TM1py/Services/SecurityService.py#L31)), the formatted values should probably be URL encoded. If a string contains, say, a question mark, it will create an invalid URL.

Python 3 `urlencode()`:
https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlencode

Python 2 `urlencode()`:
https://docs.python.org/2/library/urllib.html#urllib.urlencode

**Comment by ajmyers** [comment]
This came from the TM1py library which I bundled in for dealing with Sublime Text quirkiness. I was able to unbundle it though. Thanks!
