### ISSUE TITLE
Empty lines in process doubled?

### ISSUE THREAD

**Issue by hermie64** [ajmyers/Sublime-TM1#3]
Process in Sublime shows more empty lines than TI process and consequently after update the TI process also includes these additional empty lines.

Great work by the way!

**Comment by ajmyers** [comment]
@hermie64 Thank you for the contribution! Sorry it took so long for the fix.

**Comment by hermie64** [comment]
Hi, I installed 0.0.4 today but when pulling object from TM1 I still see empty lines that are not displayed in TI editor.
